name: todo_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_auth: ^5.3.3
  lottie: ^2.7.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0 # fireSotre연결

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/NanumSquareNeo-cBd.ttf
  uses-material-design: true
  assets:
    - assets/lottie/

